# -*- coding: utf-8 -*-
"""Fibonacci Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ghynTryTE4-hljCYbB9RJ05_cEEd9m3
"""

n = int(input())
t1 = 0
t2 = 1
for i in range(n):
  nextTerm = t1+t2
  t1 = t2
  t2 = nextTerm
print(t1)