# -*- coding: utf-8 -*-
"""Formatted Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ghynTryTE4-hljCYbB9RJ05_cEEd9m3
"""

st = input()
for i in range(len(st)):
  if (len(st)-i)%3==0 and i>0:
    print(",", end ="")
  print(st[i], end ="")