# -*- coding: utf-8 -*-
"""Is Anagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ghynTryTE4-hljCYbB9RJ05_cEEd9m3
"""

st1 = input()
st2 = input()

if len(st1)!=len(st2):
  print("No")

else:
  if sorted(st1)==sorted(st2):
    print("Yes")
  else:
    print("No")